const studentsList = [
  'Fernando Adamo',
  'Diego Aguirre',
  'Juan Carlos Almaraz',
  'Daniela Aritto',
  'Martín Barral',
  'Sergio Bianchi',
  'Ezequiel Blanco',
  'Marco Castiglione',
  'Juan Martín Domínguez',
  'Ayelén Eula',
  'Néstor David Fleitas',
  'Guido Galanternik',
  'Nicolás Giraldi',
  'José Gutiérrez Ibañez',
  'Camilo Heller',
  'Bárbara Imperatori',
  'Oliver Korn',
  'María Lucía Moreno Seoane',
  'Ezequiel Ramírez',
  'Diana Rodríguez',
  'Andrés Rojas',
  'Eduardo Sánchez',
  'Jorge Schenone',
  'Franco Taboada',
  'Eugenio Tomaso',
  'Matías Blayer',
  'Nicolás Quiroz'
]

const questionsList = [
  '¿En qué deporte creés que le podrías ganar a tu mentor/a?',
  '¿Cual es tu gusto de helado preferido? Fundamente su respuesta.',
  '¿Cuál fue la mejor película/serie que viste? (o libro que leíste)',
  '¿Qué es lo que mejor sabés cocinar?',
  'Si no vivieras en Buenos Aires, ¿dónde te gustaría vivir?',
  'Si tuvieras que elegir una sola comida para comer por el resto de tu vida, ¿cuál sería?',
  '¿Preferís el verano o el invierno? ¿Por qué?',
  'Si tuvieras la plata para poner una fábrica o un negocio, ¿de qué sería?',
  '¿A favor o en contra de las montañas rusas? ¿Por qué?',
  '¿Quién era tu ídolo/a de la infancia? ¿Por qué?',
  'Si fueras un/a superhéroe, ¿cuál sería tu superpoder?',
  '¿A quién llevarías a una isla desierta?',
  'Si tuvieses que convertirte en un animal, ¿cuál elegirías? Fundamente.',
  '¿Si pudieras viajar a cualquier época (pasado o futuro), cuándo elegirías?',
  '¿Cuál es la mejor marca de alfajor? Fundamente.',
  'Si mañana te despertás y sos invisible, ¿qué es lo primero que harías?',
  'Si la plata y el tiempo no importaran, ¿de qué te disfrazarías en una fiesta de disfraces?',
  'Si pudieras conocer a cualquier persona de la historia, ¿a quién elegirías?',
  'Si tuvieses que tirarte en una pileta repleta de algo, ¿de qué sería?',
  'Si pudieras tener flujo ilimitado de una sola cosa, ¿qué elegirías?',
  'Qué decías cuando eras chico/a y te preguntaban: ¿qué querés ser de grande?',
  '¿Cual es tu película favorita de Star Wars?'
]
